import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TravelAgency-App",
  description: "Generated by Marijana",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width" />
      <body className={inter.className}>
        <nav className="nav">
          <div className="nav-links">
            <MainNav />
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
